In [260]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [289]:
df = pd.read_csv('PrepHR.csv')
df = df.drop(columns=['Unnamed: 0','StandardHours'])

In [262]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 32 columns):
 #   Column                    Non-Null Count  Dtype 
---  ------                    --------------  ----- 
 0   Age                       1470 non-null   int64 
 1   Attrition                 1470 non-null   object
 2   BusinessTravel            1470 non-null   object
 3   DailyRate                 1470 non-null   int64 
 4   Department                1470 non-null   object
 5   DistanceFromHome          1470 non-null   int64 
 6   Education                 1470 non-null   object
 7   EducationField            1470 non-null   object
 8   EmployeeNumber            1470 non-null   int64 
 9   EnvironmentSatisfaction   1470 non-null   int64 
 10  Gender                    1470 non-null   object
 11  HourlyRate                1470 non-null   int64 
 12  JobInvolvement            1470 non-null   int64 
 13  JobLevel                  1470 non-null   int64 
 14  JobRole                 

In [263]:
df.columns

Index(['Age', 'Attrition', 'BusinessTravel', 'DailyRate', 'Department',
       'DistanceFromHome', 'Education', 'EducationField', 'EmployeeNumber',
       'EnvironmentSatisfaction', 'Gender', 'HourlyRate', 'JobInvolvement',
       'JobLevel', 'JobRole', 'JobSatisfaction', 'MaritalStatus',
       'MonthlyIncome', 'MonthlyRate', 'NumCompaniesWorked', 'OverTime',
       'PercentSalaryHike', 'PerformanceRating', 'RelationshipSatisfaction',
       'StockOptionLevel', 'TotalWorkingYears', 'TrainingTimesLastYear',
       'WorkLifeBalance', 'YearsAtCompany', 'YearsInCurrentRole',
       'YearsSinceLastPromotion', 'YearsWithCurrManager'],
      dtype='object')

In [264]:
df.BusinessTravel.unique()

array(['Travel_Rarely', 'Travel_Frequently', 'Non-Travel'], dtype=object)

In [265]:
num_col = df[['Age','DailyRate','EmployeeNumber','MonthlyIncome','MonthlyRate']]
num_col.head(5)

Age  DailyRate  EmployeeNumber  MonthlyIncome  MonthlyRate
0   41       1102               1           5993        19479
1   49        279               2           5130        24907
2   37       1373               4           2090         2396
3   33       1392               5           2909        23159
4   27        591               7           3468        16632

In [266]:
cat_col = df[['Attrition','BusinessTravel','Department','JobSatisfaction','EducationField','Gender','JobLevel','JobRole','MaritalStatus','OverTime','DistanceFromHome','Education','EnvironmentSatisfaction','RelationshipSatisfaction','StockOptionLevel','JobInvolvement','WorkLifeBalance']]
cat_col.head(5)

Attrition     BusinessTravel              Department  JobSatisfaction  \
0       Yes      Travel_Rarely                   Sales                4   
1        No  Travel_Frequently  Research & Development                2   
2       Yes      Travel_Rarely  Research & Development                3   
3        No  Travel_Frequently  Research & Development                3   
4        No      Travel_Rarely  Research & Development                2   

  EducationField  Gender  JobLevel                JobRole MaritalStatus  \
0  Life Sciences  Female         2        Sales Executive        Single   
1  Life Sciences    Male         2     Research Scientist       Married   
2          Other    Male         1  Laboratory Technician        Single   
3  Life Sciences  Female         1     Research Scientist       Married   
4        Medical    Male         1  Laboratory Technician       Married   

  OverTime  DistanceFromHome         Education  EnvironmentSatisfaction  \
0      Yes                 1  Higher Secondary                        2   
1       No                 8       High School                        3   
2      Yes                 2  Higher Secondary                        4   
3      Yes                 3           Masters                        4   
4       No                 2       High School                        1   

   RelationshipSatisfaction  StockOptionLevel  JobInvolvement  WorkLifeBalance  
0                         1                 0               3                1  
1                         4                 1               2                3  
2                         2                 0               2                3  
3                         3                 0               3                3  
4                         4                 1               3                3

In [267]:
nlcat_col = df[['HourlyRate','NumCompaniesWorked','PercentSalaryHike','TotalWorkingYears','TrainingTimesLastYear','YearsAtCompany','YearsInCurrentRole','YearsSinceLastPromotion','YearsWithCurrManager']]
nlcat_col.head(5)

HourlyRate  NumCompaniesWorked  PercentSalaryHike  TotalWorkingYears  \
0          94                   8                 11                  8   
1          61                   1                 23                 10   
2          92                   6                 15                  7   
3          56                   1                 11                  8   
4          40                   9                 12                  6   

   TrainingTimesLastYear  YearsAtCompany  YearsInCurrentRole  \
0                      0               6                   4   
1                      3              10                   7   
2                      3               0                   0   
3                      3               8                   7   
4                      3               2                   2   

   YearsSinceLastPromotion  YearsWithCurrManager  
0                        0                     5  
1                        1                     7  
2                        0                     0  
3                        3                     0  
4                        2                     2

In [268]:
df.RelationshipSatisfaction.unique()

array([1, 4, 2, 3], dtype=int64)

In [269]:
mapping = {
    1 : 'Poor',
    2: 'Good',
    3: 'Best',
    4: 'Excellent',
}

df["RelationshipSatisfaction"] = df["RelationshipSatisfaction"].map(mapping)

In [270]:
np.sort(df.DistanceFromHome.unique())

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29], dtype=int64)

In [271]:
def dfromhome(n):
    if (n > 1) & (n <= 10):
        return 'Near by'
    elif (n > 10) & (n <= 20):
        return 'Far'
    elif (n > 20) & (n <= 30):
        return 'Faraway'
    else:
        return 
    
df['DistanceFromHome'] = df['DistanceFromHome'].apply(dfromhome)

In [272]:
df.EnvironmentSatisfaction.unique()

array([2, 3, 4, 1], dtype=int64)

In [273]:
mapping = {
    1 : 'Very Low',
    2: 'Low',
    3: 'Moderate',
    4: 'High',
}

df["EnvironmentSatisfaction"] = df["EnvironmentSatisfaction"].map(mapping)

In [274]:
df.JobInvolvement.unique()

array([3, 2, 4, 1], dtype=int64)

In [275]:
mapping = {
    1 : 'Very Low',
    2: 'Low',
    3: 'Moderate',
    4: 'High',
}

df["JobInvolvement"] = df["JobInvolvement"].map(mapping)

In [276]:
df.JobLevel.unique()

array([2, 1, 3, 4, 5], dtype=int64)

In [277]:
mapping = {
    1 : 'Very Low',
    2: 'Low',
    3: 'Moderate',
    4: 'High',
    5: 'Very High'
}

df["JobLevel"] = df["JobLevel"].map(mapping)

In [303]:
df.RelationshipSatisfaction.unique()

array([1, 4, 2, 3], dtype=int64)

In [304]:
mapping = {
    1 : 'Very Low',
    2: 'Low',
    3: 'Moderate',
    4: 'High',
}

df["RelationshipSatisfaction"] = df["RelationshipSatisfaction"].map(mapping)

In [309]:
df.StockOptionLevel.unique()

array([0, 1, 3, 2], dtype=int64)

In [310]:
mapping = {
    0 : 'No',
    2: 'Low',
    3: 'Medium',
    4: 'High',
}

df["StockOptionLevel"] = df["StockOptionLevel"].map(mapping)

In [282]:
df.WorkLifeBalance.unique()

array([1, 3, 2, 4], dtype=int64)

In [283]:
mapping = {
    1: 'Poor',
    2: 'Good',
    3: 'Best',
    4: 'Excellent',
}

df["WorkLifeBalance"] = df["WorkLifeBalance"].map(mapping)

In [284]:
df.JobSatisfaction.unique()

array([4, 2, 3, 1], dtype=int64)

In [285]:

mapping = {
    1 : 'Poor',
    2 : 'Good',
    3 : 'Best',
    4 : 'Excellent',
}

df["JobSatisfaction"] = df["JobSatisfaction"].map(mapping)

In [286]:
pd.set_option('display.max_columns', None)
df.head(5)

Age Attrition     BusinessTravel  DailyRate              Department  \
0   41       Yes      Travel_Rarely       1102                   Sales   
1   49        No  Travel_Frequently        279  Research & Development   
2   37       Yes      Travel_Rarely       1373  Research & Development   
3   33        No  Travel_Frequently       1392  Research & Development   
4   27        No      Travel_Rarely        591  Research & Development   

  DistanceFromHome         Education EducationField  EmployeeNumber  \
0             None  Higher Secondary  Life Sciences               1   
1          Near by       High School  Life Sciences               2   
2          Near by  Higher Secondary          Other               4   
3          Near by           Masters  Life Sciences               5   
4          Near by       High School        Medical               7   

  EnvironmentSatisfaction  Gender  HourlyRate JobInvolvement  JobLevel  \
0                     Low  Female          94       Moderate       Low   
1                Moderate    Male          61            Low       Low   
2                    High    Male          92            Low  Very Low   
3                    High  Female          56       Moderate  Very Low   
4                Very Low    Male          40       Moderate  Very Low   

                 JobRole JobSatisfaction MaritalStatus  MonthlyIncome  \
0        Sales Executive       Excellent        Single           5993   
1     Research Scientist            Good       Married           5130   
2  Laboratory Technician            Best        Single           2090   
3     Research Scientist            Best       Married           2909   
4  Laboratory Technician            Good       Married           3468   

   MonthlyRate  NumCompaniesWorked OverTime  PercentSalaryHike  \
0        19479                   8      Yes                 11   
1        24907                   1       No                 23   
2         2396                   6      Yes                 15   
3        23159                   1      Yes                 11   
4        16632                   9       No                 12   

   PerformanceRating RelationshipSatisfaction StockOptionLevel  \
0                  3                      NaN               No   
1                  4                      NaN              NaN   
2                  3                      NaN               No   
3                  3                      NaN               No   
4                  3                      NaN              NaN   

   TotalWorkingYears  TrainingTimesLastYear WorkLifeBalance  YearsAtCompany  \
0                  8                      0            Poor               6   
1                 10                      3            Best              10   
2                  7                      3            Best               0   
3                  8                      3            Best               8   
4                  6                      3            Best               2   

   YearsInCurrentRole  YearsSinceLastPromotion  YearsWithCurrManager  
0                   4                        0                     5  
1                   7                        1                     7  
2                   0                        0                     0  
3                   7                        3                     0  
4                   2                        2                     2

In [ ]:
RelationshipSatisfaction    1470
StockOptionLevel             596
DistanceFromHome             208

In [311]:
df.StockOptionLevel.unique()

array(['No', nan, 'Medium', 'Low'], dtype=object)

In [312]:
df.RelationshipSatisfaction.sample(10)

1039        High
543     Moderate
199     Very Low
431     Moderate
100         High
816     Moderate
1317    Moderate
1456        High
821          Low
584          Low
Name: RelationshipSatisfaction, dtype: object

In [314]:
df.StockOptionLevel.isna().sum()

596