In [61]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [62]:
df = pd.read_csv('PrepHR.csv')
df = df.drop(columns=['Unnamed: 0','StandardHours'])

In [63]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 32 columns):
 #   Column                    Non-Null Count  Dtype 
---  ------                    --------------  ----- 
 0   Age                       1470 non-null   int64 
 1   Attrition                 1470 non-null   object
 2   BusinessTravel            1470 non-null   object
 3   DailyRate                 1470 non-null   int64 
 4   Department                1470 non-null   object
 5   DistanceFromHome          1470 non-null   int64 
 6   Education                 1470 non-null   object
 7   EducationField            1470 non-null   object
 8   EmployeeNumber            1470 non-null   int64 
 9   EnvironmentSatisfaction   1470 non-null   int64 
 10  Gender                    1470 non-null   object
 11  HourlyRate                1470 non-null   int64 
 12  JobInvolvement            1470 non-null   int64 
 13  JobLevel                  1470 non-null   int64 
 14  JobRole                 

In [64]:
df.columns

Index(['Age', 'Attrition', 'BusinessTravel', 'DailyRate', 'Department',
       'DistanceFromHome', 'Education', 'EducationField', 'EmployeeNumber',
       'EnvironmentSatisfaction', 'Gender', 'HourlyRate', 'JobInvolvement',
       'JobLevel', 'JobRole', 'JobSatisfaction', 'MaritalStatus',
       'MonthlyIncome', 'MonthlyRate', 'NumCompaniesWorked', 'OverTime',
       'PercentSalaryHike', 'PerformanceRating', 'RelationshipSatisfaction',
       'StockOptionLevel', 'TotalWorkingYears', 'TrainingTimesLastYear',
       'WorkLifeBalance', 'YearsAtCompany', 'YearsInCurrentRole',
       'YearsSinceLastPromotion', 'YearsWithCurrManager'],
      dtype='object')

In [65]:
df.BusinessTravel.unique()

array(['Travel_Rarely', 'Travel_Frequently', 'Non-Travel'], dtype=object)

In [66]:
num_col = df[['Age','DailyRate','EmployeeNumber','MonthlyIncome','MonthlyRate']]
num_col.head(5)

Age  DailyRate  EmployeeNumber  MonthlyIncome  MonthlyRate
0   41       1102               1           5993        19479
1   49        279               2           5130        24907
2   37       1373               4           2090         2396
3   33       1392               5           2909        23159
4   27        591               7           3468        16632

In [67]:
cat_col = df[['Attrition','BusinessTravel','Department','JobSatisfaction','EducationField','Gender','JobLevel','JobRole','MaritalStatus','OverTime','DistanceFromHome','Education','EnvironmentSatisfaction','RelationshipSatisfaction','StockOptionLevel','JobInvolvement','WorkLifeBalance']]
cat_col.head(5)

Attrition     BusinessTravel              Department  JobSatisfaction  \
0       Yes      Travel_Rarely                   Sales                4   
1        No  Travel_Frequently  Research & Development                2   
2       Yes      Travel_Rarely  Research & Development                3   
3        No  Travel_Frequently  Research & Development                3   
4        No      Travel_Rarely  Research & Development                2   

  EducationField  Gender  JobLevel                JobRole MaritalStatus  \
0  Life Sciences  Female         2        Sales Executive        Single   
1  Life Sciences    Male         2     Research Scientist       Married   
2          Other    Male         1  Laboratory Technician        Single   
3  Life Sciences  Female         1     Research Scientist       Married   
4        Medical    Male         1  Laboratory Technician       Married   

  OverTime  DistanceFromHome         Education  EnvironmentSatisfaction  \
0      Yes                 1  Higher Secondary                        2   
1       No                 8       High School                        3   
2      Yes                 2  Higher Secondary                        4   
3      Yes                 3           Masters                        4   
4       No                 2       High School                        1   

   RelationshipSatisfaction  StockOptionLevel  JobInvolvement  WorkLifeBalance  
0                         1                 0               3                1  
1                         4                 1               2                3  
2                         2                 0               2                3  
3                         3                 0               3                3  
4                         4                 1               3                3

In [68]:
nlcat_col = df[['HourlyRate','NumCompaniesWorked','PercentSalaryHike','TotalWorkingYears','TrainingTimesLastYear','YearsAtCompany','YearsInCurrentRole','YearsSinceLastPromotion','YearsWithCurrManager']]
nlcat_col.head(5)

HourlyRate  NumCompaniesWorked  PercentSalaryHike  TotalWorkingYears  \
0          94                   8                 11                  8   
1          61                   1                 23                 10   
2          92                   6                 15                  7   
3          56                   1                 11                  8   
4          40                   9                 12                  6   

   TrainingTimesLastYear  YearsAtCompany  YearsInCurrentRole  \
0                      0               6                   4   
1                      3              10                   7   
2                      3               0                   0   
3                      3               8                   7   
4                      3               2                   2   

   YearsSinceLastPromotion  YearsWithCurrManager  
0                        0                     5  
1                        1                     7  
2                        0                     0  
3                        3                     0  
4                        2                     2

In [69]:
df.RelationshipSatisfaction.unique()

array([1, 4, 2, 3])

In [70]:
mapping = {
    1: 'Poor',
    2: 'Good',
    3: 'Best',
    4: 'Excellent',
}

df["RelationshipSatisfaction"] = df["RelationshipSatisfaction"].map(mapping)

In [71]:
np.sort(df.DistanceFromHome.unique())

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [72]:
def dfromhome(n):
    if (n >= 1) & (n <= 10):
        return 'Near by'
    elif (n >= 10) & (n <= 20):
        return 'Far'
    elif (n >= 20) & (n <= 30):
        return 'Faraway'
    else:
        return 0
    
df['DistanceFromHome'] = df['DistanceFromHome'].apply(dfromhome)

In [73]:
df.EnvironmentSatisfaction.unique()

array([2, 3, 4, 1])

In [74]:
mapping = {
    1: 'Poor',
    2: 'Good',
    3: 'Best',
    4: 'Excellent',
}

df["EnvironmentSatisfaction"] = df["EnvironmentSatisfaction"].map(mapping)

In [75]:
df.JobInvolvement.unique()

array([3, 2, 4, 1])

In [76]:
mapping = {
    1 : 'Very Low',
    2: 'Low',
    3: 'Moderate',
    4: 'High',
}

df["JobInvolvement"] = df["JobInvolvement"].map(mapping)

In [77]:
df.JobLevel.unique()

array([2, 1, 3, 4, 5])

In [78]:
mapping = {
    1: 'Beginner',
    2: 'Intermediate',
    3: 'Experienced',
    4: 'Advanced',
    5: 'Expert'
}

df["JobLevel"] = df["JobLevel"].map(mapping)

In [79]:
df.StockOptionLevel.unique()

array([0, 1, 3, 2])

In [80]:
mapping = {
    0 : 'No',
    1: 'Low',
    2: 'Medium',
    3: 'High',
}

df["StockOptionLevel"] = df["StockOptionLevel"].map(mapping)

In [81]:
df.WorkLifeBalance.unique()

array([1, 3, 2, 4])

In [82]:
mapping = {
    1: 'Poor',
    2: 'Good',
    3: 'Best',
    4: 'Excellent',
}

df["WorkLifeBalance"] = df["WorkLifeBalance"].map(mapping)

In [83]:
df.JobSatisfaction.unique()

array([4, 2, 3, 1])

In [84]:

mapping = {
    1 : 'Poor',
    2 : 'Good',
    3 : 'Best',
    4 : 'Excellent',
}

df["JobSatisfaction"] = df["JobSatisfaction"].map(mapping)

In [85]:
pd.set_option('display.max_columns', None)
df.head(5)

Age Attrition     BusinessTravel  DailyRate              Department  \
0   41       Yes      Travel_Rarely       1102                   Sales   
1   49        No  Travel_Frequently        279  Research & Development   
2   37       Yes      Travel_Rarely       1373  Research & Development   
3   33        No  Travel_Frequently       1392  Research & Development   
4   27        No      Travel_Rarely        591  Research & Development   

  DistanceFromHome         Education EducationField  EmployeeNumber  \
0          Near by  Higher Secondary  Life Sciences               1   
1          Near by       High School  Life Sciences               2   
2          Near by  Higher Secondary          Other               4   
3          Near by           Masters  Life Sciences               5   
4          Near by       High School        Medical               7   

  EnvironmentSatisfaction  Gender  HourlyRate JobInvolvement      JobLevel  \
0                    Good  Female          94       Moderate  Intermediate   
1                    Best    Male          61            Low  Intermediate   
2               Excellent    Male          92            Low      Beginner   
3               Excellent  Female          56       Moderate      Beginner   
4                    Poor    Male          40       Moderate      Beginner   

                 JobRole JobSatisfaction MaritalStatus  MonthlyIncome  \
0        Sales Executive       Excellent        Single           5993   
1     Research Scientist            Good       Married           5130   
2  Laboratory Technician            Best        Single           2090   
3     Research Scientist            Best       Married           2909   
4  Laboratory Technician            Good       Married           3468   

   MonthlyRate  NumCompaniesWorked OverTime  PercentSalaryHike  \
0        19479                   8      Yes                 11   
1        24907                   1       No                 23   
2         2396                   6      Yes                 15   
3        23159                   1      Yes                 11   
4        16632                   9       No                 12   

   PerformanceRating RelationshipSatisfaction StockOptionLevel  \
0                  3                     Poor               No   
1                  4                Excellent              Low   
2                  3                     Good               No   
3                  3                     Best               No   
4                  3                Excellent              Low   

   TotalWorkingYears  TrainingTimesLastYear WorkLifeBalance  YearsAtCompany  \
0                  8                      0            Poor               6   
1                 10                      3            Best              10   
2                  7                      3            Best               0   
3                  8                      3            Best               8   
4                  6                      3            Best               2   

   YearsInCurrentRole  YearsSinceLastPromotion  YearsWithCurrManager  
0                   4                        0                     5  
1                   7                        1                     7  
2                   0                        0                     0  
3                   7                        3                     0  
4                   2                        2                     2

RelationshipSatisfaction    1470
StockOptionLevel             596
DistanceFromHome             208

In [86]:
df.isna().sum()

Age                         0
Attrition                   0
BusinessTravel              0
DailyRate                   0
Department                  0
DistanceFromHome            0
Education                   0
EducationField              0
EmployeeNumber              0
EnvironmentSatisfaction     0
Gender                      0
HourlyRate                  0
JobInvolvement              0
JobLevel                    0
JobRole                     0
JobSatisfaction             0
MaritalStatus               0
MonthlyIncome               0
MonthlyRate                 0
NumCompaniesWorked          0
OverTime                    0
PercentSalaryHike           0
PerformanceRating           0
RelationshipSatisfaction    0
StockOptionLevel            0
TotalWorkingYears           0
TrainingTimesLastYear       0
WorkLifeBalance             0
YearsAtCompany              0
YearsInCurrentRole          0
YearsSinceLastPromotion     0
YearsWithCurrManager        0
dtype: int64

In [87]:
df.sample(5)

Age Attrition     BusinessTravel  DailyRate              Department  \
391    40        No      Travel_Rarely        555  Research & Development   
1023   56        No      Travel_Rarely       1255  Research & Development   
660    58       Yes  Travel_Frequently        781  Research & Development   
538    41        No      Travel_Rarely        314         Human Resources   
1131   34        No  Travel_Frequently        653  Research & Development   

     DistanceFromHome         Education    EducationField  EmployeeNumber  \
391           Near by        Bacherlors           Medical             521   
1023          Near by  Higher Secondary     Life Sciences            1441   
660           Near by       High School     Life Sciences             918   
538           Near by        Bacherlors   Human Resources             734   
1131          Near by           Masters  Technical Degree            1597   

     EnvironmentSatisfaction  Gender  HourlyRate JobInvolvement      JobLevel  \
391                     Good  Female          78            Low  Intermediate   
1023                    Poor  Female          90       Moderate      Beginner   
660                Excellent    Male          57            Low      Beginner   
538                Excellent    Male          59            Low        Expert   
1131               Excellent    Male          92            Low  Intermediate   

                        JobRole JobSatisfaction MaritalStatus  MonthlyIncome  \
391       Laboratory Technician            Best       Married           3448   
1023         Research Scientist            Poor       Married           2066   
660       Laboratory Technician       Excellent      Divorced           2380   
538                     Manager            Best       Married          19189   
1131  Healthcare Representative            Best       Married           5063   

      MonthlyRate  NumCompaniesWorked OverTime  PercentSalaryHike  \
391         13436                   6       No                 22   
1023        10494                   2       No                 22   
660         13384                   9      Yes                 14   
538         19562                   1       No                 12   
1131        15332                   1       No                 14   

      PerformanceRating RelationshipSatisfaction StockOptionLevel  \
391                   4                     Good              Low   
1023                  4                Excellent              Low   
660                   3                Excellent              Low   
538                   3                     Good              Low   
1131                  3                     Good              Low   

      TotalWorkingYears  TrainingTimesLastYear WorkLifeBalance  \
391                  20                      3            Best   
1023                  5                      3       Excellent   
660                   3                      3            Good   
538                  22                      3            Best   
1131                  8                      3            Good   

      YearsAtCompany  YearsInCurrentRole  YearsSinceLastPromotion  \
391                1                   0                        0   
1023               3                   2                        1   
660                1                   0                        0   
538               22                   7                        2   
1131               8                   2                        7   

      YearsWithCurrManager  
391                      0  
1023                     0  
660                      0  
538                     10  
1131                     7